language: cpp
sudo: false
osx_image: xcode7
cache:
  directories:
  - container
matrix:
  include:
  - os: linux
    env: CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1" CMAKE_C_COMPILER="clang-3.8" CMAKE_CXX_COMPILER="clang++-3.8"
  - os: linux
    env: CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest" CMAKE_C_COMPILER="clang-3.8" CMAKE_CXX_COMPILER="clang++-3.8"
  - os: linux
    env: CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0" CMAKE_C_COMPILER="clang-3.8" CMAKE_CXX_COMPILER="clang++-3.8"
  - os: linux
    env: CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0" CMAKE_C_COMPILER="clang-3.8" CMAKE_CXX_COMPILER="clang++-3.8"
  - os: linux
    env: CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage" CMAKE_C_COMPILER="clang-3.8" CMAKE_CXX_COMPILER="clang++-3.8"
  - os: osx
    env: CMAKE_GENERATOR="Xcode" CMAKE_VERSION="latest"
env:
  global:
  - secure: JEjMUojp81OtlxeljKhbEg96Z1gRm2G4ToDeO3BmNZ9iAbFEArr6ZUSKPJzv56kdV1mkgh0EQzOo4BnCO19A8+WiRTfi1+ZdLvd7p+lcGx8iJctZtwhlfmaDR87MXFZYP3LvKASwa2VTi/jqmtsNYes1/+ti5wfwEWbMICaPZ90=
  - secure: IJJ9zobPHIDnvTClcZhVkIFwS6hhMHVT3klvAAeAreummaYa4GHYcyD82FT/ooMeUjLnoK+9hiIb3fWZvsVo+axdEJPOHdQ+h0s1hNEIq1pSQIwA1abMvpMuNvkoYrKGb4pygyE4tYlJqGmyfHXGhlo0Li84qQ5JKsmQVL4CZh8=
  - secure: LeF41KFO1TSLLtSWv5zCt9BKEZv3/ERhgV4NKhpZMPf7IkwIT5yR5/sS2qSS9WJO6Sr0S+ExyXHw+HqW8h/dteoZ0puw2b7AUEkENb6KU6/PqO/FufWB3iUSczOEq+xl0BKZ5K6wzKOE+l0Xtujm2vla8qa9CD0sKXqBaURSSmQ=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace psq --generator
  "${CMAKE_GENERATOR}" --cmake-cache-variables "CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}" "CMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package="common-universal-cmake"
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis-deploy"
  on:
    repo: polysquare/common-universal-cmake
    branch: master
    condition: "${DEPLOY} = 1"
